services:
  - type: web
    name: clanteamfc
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://qpraaostmojllbgfczox.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
